version: 2

sources:
  - name: bronze
    database: awesomeinc
    schema: public
    tables:
      - name: country
        description: Country table
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
              - unique
          - name: region
            tests:
              - not_null

      - name: customer
        description: Customer table
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
          - name: email
            tests:
              - not_null
              - unique
          - name: country_id
            tests:
              - not_null
          - name: premium_customer
            tests:
              - not_null
              - accepted_values:
                  values: ["yes", "no"]

      - name: installation
        description: Installation table
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
          - name: description
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: customer_id
            tests:
              - not_null
          - name: installation_date
            tests:
              - not_null

      - name: product
        description: Product table
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: reference
            tests:
              - not_null
          - name: name
            tests:
              - not_null
          - name: category_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null

      - name: product_category
        description: Product category table
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
