awesome_inc:
  outputs:
    dev:
      dbname: "{{ env_var('DATABASE__DB') }}"
      host: "{{ env_var('DATABASE__HOSTNAME') }}"
      pass: "{{ env_var('DATABASE__PASSWORD') }}"
      port: "{{ env_var('DATABASE__PORT') | int }}"
      user: "{{ env_var('DATABASE__USERNAME') }}"
      schema: warehouse
      threads: 1
      type: postgres
  target: dev
