name: "tests"
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set environment variables
        uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: .env
      - name: Install rye
        uses: eifinger/setup-rye@v3
        with:
          version: "latest"
      - name: Install rye dependencies
        run: rye sync
      - name: Run pre-commit CI hooks
        run: rye run pre-commit run --all-files
